apiVersion: v1
kind: Service
metadata:
  name: mongo-shardsctl-slb
  labels:
    name: mongo-shardsctl-slb
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: slb
  sessionAffinity: None
  type: ClusterIP

---

#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo-shardsctl-svc1
#  labels:
#    name: mongo-shardsctl-svc1
#spec:
#  clusterIP: None
#  ports:
#  - port: 27017
#    targetPort: 27017
#    protocol: TCP
#  selector:
#    name: mongo-shardsctl1
#---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shardsctl-rc1
  labels:
    name: mongo-shardsctl-rc1
    app: slb
spec:
  replicas: 1
  selector:
    name: mongo-shardsctl1
  template:
    metadata:
      labels:
        name: mongo-shardsctl1
        app: slb
    spec:
      containers:
      - name: mongo-shardsctl1
        image: registry.dataos.io/liuliu/mongos
        livenessProbe:
          tcpSocket:
            port: 27017
        args:
#        - mongos
        - "--configdb"
        - "mongo-configsvc-0:27019,mongo-configsvc-1:27019,mongo-configsvc-2:27019"
        - "--port=27017"
        ports:
        - containerPort: 27017

---


#apiVersion: v1
#kind: Service
#metadata:
#  name: mongo-shardsctl-svc2
#  labels:
#    name: mongo-shardsctl-svc2
#spec:
#  clusterIP: None
#  ports:
#  - port: 27017
#    targetPort: 27017
#    protocol: TCP
#  selector:
#    name: mongo-shardsctl2
#---

apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shardsctl-rc2
  labels:
    name: mongo-shardsctl-rc2
    app: slb
spec:
  replicas: 1
  selector:
    name: mongo-shardsctl2
  template:
    metadata:
      labels:
        name: mongo-shardsctl2
        app: slb
    spec:
      containers:
      - name: mongo-shardsctl2
        image: registry.dataos.io/liuliu/mongos
        livenessProbe:
          initialDelaySeconds: 20
          timeoutSeconds: 5
          tcpSocket:
            port: 27017
        args:
#        - mongos
        - "--configdb"
        - "mongo-configsvc-0:27019,mongo-configsvc-1:27019,mongo-configsvc-2:27019"
        - "--port=27017"
        ports:
        - containerPort: 27017

