#3 mongodb instances consist a replica set : "my_replica_set"
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-nodea-0
  labels:
    name: mongo-svca
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-nodea0
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-nodea-1
  labels:
    name: mongo-svca
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-nodea1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-nodea-2
  labels:
    name: mongo-svca
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-nodea2
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rca1
  labels:
    name: mongo-replica-rca
spec:
  replicas: 1
  selector:
    name: mongo-replica-nodea0
  template:
    metadata:
      labels:
        name: mongo-replica-nodea0
    spec:
      containers:
      - name: mongo-replica-nodea0
        image: registry.dataos.io/liuliu/mongod-replica-set:3.2.10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 50
          timeoutSeconds: 10
        env:
          - name: mongo_node_name
            value: mongo-replica-nodea
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage0
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage0
#        emptyDir: {}
        persistentVolumeClaim:
          claimName: mongo-storage1-1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rca2
  labels:
    name: mongo-replica-rca
spec:
  replicas: 1
  selector:
    name: mongo-replica-nodea1
  template:
    metadata:
      labels:
        name: mongo-replica-nodea1
    spec:
      containers:
      - name: mongo-replica-nodea1
        image: registry.dataos.io/liuliu/mongod-replica-set:3.2.10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 50
          timeoutSeconds: 10
        env:
          - name: mongo_node_name
            value: mongo-replica-nodea
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage1
#        emptyDir: {}
        persistentVolumeClaim:
          claimName: mongo-storage1-2

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rca3
  labels:
    name: mongo-replica-rca
spec:
  replicas: 1
  selector:
    name: mongo-replica-nodea2
  template:
    metadata:
      labels:
        name: mongo-replica-nodea2
    spec:
      containers:
      - name: mongo-replica-nodea2
        image: registry.dataos.io/liuliu/mongod-replica-set:3.2.10
        livenessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 50
          timeoutSeconds: 10
        env:
          - name: mongo_node_name
            value: mongo-replica-nodea
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set1
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage2
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage2
#        emptyDir: {}
        persistentVolumeClaim:
          claimName: mongo-storage1-3
