#3 mongodb instances consist a replica set : "my_replica_set"
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-node-0
  labels:
    name: mongo-svc
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-node0
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-node-1
  labels:
    name: mongo-svc
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-node1
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-replica-node-2
  labels:
    name: mongo-svc
spec:
  clusterIP: None
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
    name: mongo-svc-port
  selector:
    name: mongo-replica-node2
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc1
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node0
  template:
    metadata:
      labels:
        name: mongo-replica-node0
    spec:
      containers:
      - name: mongo-replica-node0
        image: registry.dataos.io/liuliu/mongo-replica-20161010
        livenessProbe:
          initialDelaySeconds: 50
          timeoutSeconds: 10
          tcpSocket:
            port: 27017
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage0
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage0
        persistentVolumeClaim:
          claimName: mongo-test1
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc2
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node1
  template:
    metadata:
      labels:
        name: mongo-replica-node1
    spec:
      containers:
      - name: mongo-replica-node1
        image: registry.dataos.io/liuliu/mongo-replica-20161010
        livenessProbe:
          initialDelaySeconds: 50
          timeoutSeconds: 10
          tcpSocket:
            port: 27017
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage1
        persistentVolumeClaim:
          claimName: mongo-test2

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc3
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node2
  template:
    metadata:
      labels:
        name: mongo-replica-node2
    spec:
      containers:
      - name: mongo-replica-node2
        image: registry.dataos.io/liuliu/mongo-replica-20161010
        livenessProbe:
          initialDelaySeconds: 50
          timeoutSeconds: 10
          tcpSocket:
            port: 27017
        env:
          - name: mongo_node_name
            value: mongo-replica-node
          - name: mongo_nodes_number
            value: "3"
          - name: mongo_replica_set_name
            value: my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage2
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage2
        persistentVolumeClaim:
          claimName: mongo-test3
