apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-test3
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: glusterfs-cluster
    path: mongo-test3
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle

